### ISSUE TITLE
Taskマイグレーションの作成

### ISSUE THREAD

**Issue by yumekiti** [yumekiti/hw_sub_mgmt#3]
# Taskマイグレーションの作成
## モデルとマイグレーションの作成
```
php artisan make:model Task --migration
```

### tasks(課題)
| name | type | unique | nullable |
|-|-|-|-|
| id | bigIncrements | yes|
| lesson_id | bigInt |||
| user_id | bigInt |||
| achievement_count | Int |
| timestamps |

**Comment by hanezumi** [comment]
完成した
